# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/users_roaming/alaurette/Documents/LauExchange_v2/client/ui/main.ui'
#
# Created: Tue Jun 16 18:26:41 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.mailbox = QtWidgets.QWidget()
        self.mailbox.setObjectName("mailbox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.mailbox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.splitter_2 = QtWidgets.QSplitter(self.mailbox)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.trw_mailbox = QtWidgets.QTreeWidget(self.verticalLayoutWidget_2)
        self.trw_mailbox.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.trw_mailbox.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.trw_mailbox.setProperty("showDropIndicator", False)
        self.trw_mailbox.setAlternatingRowColors(True)
        self.trw_mailbox.setItemsExpandable(False)
        self.trw_mailbox.setObjectName("trw_mailbox")
        self.verticalLayout_7.addWidget(self.trw_mailbox)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.txe_mailbox_content = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_3)
        self.txe_mailbox_content.setReadOnly(True)
        self.txe_mailbox_content.setObjectName("txe_mailbox_content")
        self.verticalLayout_8.addWidget(self.txe_mailbox_content)
        self.pub_import_attachment = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pub_import_attachment.setObjectName("pub_import_attachment")
        self.verticalLayout_8.addWidget(self.pub_import_attachment)
        self.verticalLayout_9.addWidget(self.splitter_2)
        self.tabWidget.addTab(self.mailbox, "")
        self.outbox = QtWidgets.QWidget()
        self.outbox.setObjectName("outbox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.outbox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter = QtWidgets.QSplitter(self.outbox)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lie_search_receiver = QtWidgets.QLineEdit(self.groupBox_3)
        self.lie_search_receiver.setObjectName("lie_search_receiver")
        self.verticalLayout_5.addWidget(self.lie_search_receiver)
        self.lst_all_receiver = QtWidgets.QListWidget(self.groupBox_3)
        self.lst_all_receiver.setDragEnabled(True)
        self.lst_all_receiver.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lst_all_receiver.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lst_all_receiver.setObjectName("lst_all_receiver")
        self.verticalLayout_5.addWidget(self.lst_all_receiver)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lst_receiver = QtWidgets.QListWidget(self.groupBox)
        self.lst_receiver.setDragEnabled(True)
        self.lst_receiver.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.lst_receiver.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.lst_receiver.setObjectName("lst_receiver")
        self.verticalLayout_3.addWidget(self.lst_receiver)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.txe_chat_view = QtWidgets.QTextEdit(self.groupBox_2)
        self.txe_chat_view.setReadOnly(False)
        self.txe_chat_view.setObjectName("txe_chat_view")
        self.verticalLayout_4.addWidget(self.txe_chat_view)
        self.pub_send = QtWidgets.QPushButton(self.groupBox_2)
        self.pub_send.setObjectName("pub_send")
        self.verticalLayout_4.addWidget(self.pub_send)
        self.verticalLayout_6.addWidget(self.splitter)
        self.tabWidget.addTab(self.outbox, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "LauExchange", None, -1))
        self.trw_mailbox.setSortingEnabled(True)
        self.trw_mailbox.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "From", None, -1))
        self.trw_mailbox.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Date", None, -1))
        self.pub_import_attachment.setText(QtWidgets.QApplication.translate("MainWindow", "Import attachment", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mailbox), QtWidgets.QApplication.translate("MainWindow", "Mailbox", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("MainWindow", "All reiciver", None, -1))
        self.lie_search_receiver.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Search Someone", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "To", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Message", None, -1))
        self.pub_send.setText(QtWidgets.QApplication.translate("MainWindow", "Send", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.outbox), QtWidgets.QApplication.translate("MainWindow", "Outbox", None, -1))

